version: '3.8'

services:
  postgres-messageBroker:
    image: bitnami/postgresql:latest
    ports:
      - '5456:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - 'messageBroker_pg_data:/bitnami/postgresql'

  redis-messageBroker:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
    volumes:
      - 'messageBroker_redis_data:/bitnami/redis/data'

volumes:
  messageBroker_pg_data:
  messageBroker_redis_data: